[tool.black]
line-length = 79
skip-string-normalization = true
extend-exclude = 'tests|migrations'

[tool.isort]
profile = "black"
line_length = 79
src_paths = ["backend"]
extend_skip = ["tests", "migrations"]

[tool.pytest.ini_options]
pythonpath = ["backend"]
testpaths = ["tests"]
python_files = ["test_*.py"]
required_plugins = ["pytest-django", "pytest-env"]
DJANGO_SETTINGS_MODULE = "foodgram.settings"
env = ["DJANGO_USE_SQLITE=True"]
addopts = "-vv -p no:cacheprovider"
