version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    extends:
      file: docker-compose.yml
      service: db
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
      ]
    ports:
      - 5678:5678
  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx