version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
  backend:
    image: monktime/recipeshare_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/backend_media
      - ./data/:/backend_data
  frontend:
    image: monktime/recipeshare_frontend
    volumes:
      - static:/app/result_build
  nginx:
    image: nginx:1.19.3
    ports:
      - 10000:80
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/static/api/docs
      - static:/static
      - media:/media
