# Generated by Django 4.2.4 on 2023-08-08 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            'recipes',
            '0002_recipe_recipeingredient_recipe_ingredients_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(
                db_table='recipes_favorited',
                related_name='favorited',
                to=settings.AUTH_USER_MODEL,
                verbose_name='В избранном у пользователей',
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='in_shopping_cart',
            field=models.ManyToManyField(
                db_table='recipes_shopping_cart',
                related_name='shopping_cart',
                to=settings.AUTH_USER_MODEL,
                verbose_name='В корзине у пользователей',
            ),
        ),
    ]
